# German to English mappings for Pokemon TCG Pocket cards
# IMPORTANT: More specific mappings should come FIRST (before generic types)

GERMAN_TO_ENGLISH = {
    # === SPECIFIC TRAINER CARD NAMES (must come before generic types) ===
    # Pokemon Tools - specific names
    'riesige robe': 'Giant Cape',
    'pokémon-ausrüstung': 'Giant Cape',
    'pokémonausristung': 'Giant Cape',
    'pokémon-ausrüstung': 'Giant Cape',
    'pokémon ausrüstung': 'Giant Cape',
    
    # Supporters - specific names  
    'rupel von team rocket': 'Team Rocket Grunt',
    'rüpel von team rocket': 'Team Rocket Grunt',
    'rpel von team rocket': 'Team Rocket Grunt',
    'forschung des professors': 'Professor\'s Research',
    
    # Items - specific names
    'rad des zufalls': 'Randomizor',
    'sonderbonbon': 'Rare Candy',
    'pokemon-kommunikation': 'Pokémon Communication',
    'pokémon-kommunikation': 'Pokémon Communication',
    
    # === TRAINER CARD TYPES (generic - only if no specific match) ===
    'unterstutzer': 'Supporter',
    'unterstützer': 'Supporter',
    'unterstitzer': 'Supporter',
    'stadion': 'Stadium',
    'item': 'Item',
    'werkzeug': 'Pokemon Tool',
    
    # === TRAINER CARD NAMES (German → English) ===
    # From pokemongohub.net German database
    
    # Items (Items)
    'trank': 'Potion',
    'x-initiative': 'X Attack',
    'handperiskop': 'Hand Scope',
    'pokédex': 'Pokédex',
    'pokédex': 'Pokédex', 
    'pokeball': 'Poké Ball',
    'rote karte': 'Red Card',
    'helixfossil': 'Helix Fossil',
    'domfossil': 'Dome Fossil',
    'altbernstein': 'Old Amber',
    'pokemon-flöte': 'Pokémon Flute',
    'pokémon-flöte': 'Pokémon Flute',
    'mythische tafel': 'Mythical Slab',
    'kopffossil': 'Skull Fossil',
    'panzerfossil': 'Armor Fossil',
    'pokemon-kommunikation': 'Pokémon Communication',
    'pokémon-kommunikation': 'Pokémon Communication',
    'maxi-malasada': 'Big Malasada',
    'fischernetz': 'Fishing Net',
    'sonderbonbon': 'Rare Candy',
    'rotom-pokedex': 'Rotom Dex',
    'rotom-pokédex': 'Rotom Dex',
    'schutz': 'Protect',
    'evoli-rucksack': 'Eevee Bag',
    'elementartausch': 'Elemental Switch',
    'schiggykanne': 'Squirt Bottle',
    'gummiboot': 'Inflatable Boat',
    'rad des zufalls': 'Randomizor',
    'federfossil': 'Feather Fossil',
    'schlagender hammer': 'Heavy Ball',
    'schildfossil': 'Shield Fossil',
    'clemonts backpack': 'Clemont\'s Backpack',
    'quick-grow extract': 'Quick-Grow Extract',
    
    # Pokemon Tools (Ausrüstung)
    'riesige robe': 'Giant Cape',
    'beulenhelm': 'Rocky Helmet',
    'prunusbeere': 'Roseli Berry',
    'giftstich': 'Poison Barb',
    'blatterumhang': 'Leaf Cape',
    'blätterumhang': 'Leaf Cape',
    'elektrokabel': 'Electrical Cord',
    'bestienit': 'Beastite',
    'uberbleibsel': 'Leftovers',
    'überreste': 'Leftovers',
    'stählerne schürze': 'Steel Apron',
    'dunkler anhänger': 'Dark Pendant',
    'rettender schal': 'Rescue Scarf',
    'gedächtnislicht': 'Memory Light',
    'flammenpflaster': 'Flame Orb',
    'tsitrubeere': 'Sitrus Berry',
    'schwerer helm': 'Heavy Barrel',
    'glückshandschuhe': 'Lucky Gloves',
    
    # Supporters (Unterstützer)
    'forschung des professors': 'Professor\'s Research',
    'erika': 'Erika',
    'misty': 'Misty',
    'pyro': 'Blaine',
    'koga': 'Koga',
    'giovanni': 'Giovanni',
    'rocko': 'Brock',
    'sabrina': 'Sabrina',
    'major bob': 'Major Bob',
    'abenteurer-neuling': 'Budding Expeditioner',
    'blau': 'Blue',
    'leaf': 'Leaf',
    'zyrus': 'Cyrus',
    'rüpel von team galaktik': 'Team Galactic Grunt',
    'rpel von team galaktik': 'Team Galactic Grunt',
    'cynthia': 'Cynthia',
    'volkner': 'Volkner',
    'lucia': 'Dawn',
    'mars': 'Mars',
    'perla': 'Pearl',
    'älteste von elyses': 'Celestic Town Elder',
    'barry': 'Barry',
    'diam': 'Adaman',
    'enigmara': 'Enigmara',
    'pokemon-center-dame': 'Pokémon Center Lady',
    'rot': 'Red',
    'rüpel von team rocket': 'Team Rocket Grunt',
    'rpel von team rocket': 'Team Rocket Grunt',
    'lola': 'Lola',
    'elima': 'Ilima',
    'kiawe': 'Kiawe',
    'bromley': 'Whitney',
    'tracy': 'Tracy',
    'chrys': 'Morty',
    'maho': 'Mallow',
    'lilly': 'Lillie',
    'gladio': 'Gladion',
    'lebelle': 'Lisia',
    'samantha': 'Sightseer',
    'tali': 'Thalia',
    'cosima': 'Cosima',
    'willi': 'Will',
    'silber': 'Silver',
    'angler': 'Fisher',
    'jasmin': 'Jasmine',
    'wanderer': 'Hiker',
    'bianka': 'Bianca',
    'reisende händlerin': 'Traveling Merchant',
    'jens': 'Julius',
    'benson': 'Benson',
    'hala': 'Hala',
    'maike': 'Marley',
    'lamina': 'Lana',
    'nachahmerin': 'Mimikyu',
    'xenia': 'Nina',
    'clemont': 'Clemont',
    'serena': 'Serena',
    
    # Stadiums (Stadien)
    'trainingsbereich': 'Training Area',
    'kampfplatz': 'Battle Arena',
    'aren': 'Arena',
    'platz': 'Ground',
    'kampfstadion': 'Battle Arena',
    'stadtplatz': 'Town Square',
    'startfeld': 'Starter Field',
    
    # Team Rocket
    'rupel von team rocket': 'Team Rocket Grunt',
    'team rocket grunt': 'Team Rocket Grunt',
    
    # Item names
    'rad des zufalls': 'Randomizor',
    'rad des': 'Randomizor',
    'zufalls': 'Randomizor',
    'randomizor': 'Randomizor',
    
    # Supporters
    'forschung des professors': "Professor's Research",
    'rote karte': 'Red Card',
    'x-initiative': 'X Attack',
    'trank': 'Potion',
    'sommerfest': 'Summer Festival',
    'winterdorf': 'Winter Village',
    'herbstdorf': 'Autumn Village',
    'frühlingsdorf': 'Spring Village',
    'boss-order': 'Boss\'s Orders',
    'gia': 'Giovanni',
    'lilian': 'Lilies',
    'kamala': 'Camila',
    ' Scherbe': 'Shard',
    'morgen': 'Morning',
    'nacht': 'Night',
    'sonnenuntergang': 'Sunset',
    
    # Items
    'riesige robe': 'Giant Cape',
    'riesensonde': 'Giant Cape',
    'beulenhelm': 'Rocky Helmet',
    'prunusbeere': 'Roseli Berry',
    'pokémon-kommunikation': 'Pokémon Communication',
    'pokéball': 'Poké Ball',
    'handperiskop': 'Hand Scope',
    'pokédex': 'Pokédex',
    'potion': 'Potion',
    'switch': 'Switch',
    'rare candy': 'Rare Candy',
    'energiekugel': 'Energy Sphere',
    'energiekarten': 'Energy Card',
    'notfall': 'Emergency',
    'flucht': 'Escape',
    'fänger': 'Capture',
    'fangkarte': 'Capture Mark',
    'schutz': 'Protect',
    'schilde': 'Shield',
    'koffer': 'Case',
    'tasche': 'Bag',
    'taschentuch': 'Handkerchief',
    'karte': 'Card',
    'fee': 'Fairy',
    'fee-ex': 'Pokemon Tool',
    'pikachu': 'Pokemon Tool',
    'sanktion': 'Sanity',
    'müll': 'Trash',
    'block': 'Block',
    'knirscher': 'Crunch',
    'donner': 'Thunder',
    'blitz': 'Lightning',
    'flammen': 'Flame',
    'eis': 'Ice',
    'klingen': 'Blade',
    'schwert': 'Sword',
    'schild': 'Shield',
    'panzer': 'Armor',
    'krallen': 'Claws',
    'zahn': 'Fang',
    'flügel': 'Wing',
    'schwanz': 'Tail',
    'herz': 'Heart',
    'geist': 'Ghost',
    'seele': 'Soul',
    'kraft': 'Power',
    'stark': 'Strong',
    'schnell': 'Quick',
    'leise': 'Quiet',
    'laut': 'Loud',
    'klein': 'Small',
    'groß': 'Big',
    'riesen': 'Giant',
    'mini': 'Mini',
    'ultra': 'Ultra',
    'hyper': 'Hyper',
    'max': 'Max',
    
    # Pokemon Tools (Ausrüstung)
    'ausrüstung': 'Pokemon Tool',
    'ausristung': 'Pokemon Tool',
    'pokemon-werkzeug': 'Pokemon Tool',
    'pokémon-werkzeug': 'Pokemon Tool',
    'pokémon-ex': 'Pokemon Tool',
    'pokemon-ex': 'Pokemon Tool',
    
    # === GERMAN POKEMON NAMES ===
    'bisasam': 'Bulbasaur',
    'bisaknosp': 'Ivysaur',
    'bisaflor': 'Venusaur',
    'bisaflor-ex': 'Venusaur ex',
    'raupy': 'Caterpie',
    'safcon': 'Metapod',
    'smettbo': 'Butterfree',
    'hornliu': 'Weedle',
    'kokuna': 'Kakuna',
    'bibor': 'Beedrill',
    'myrapla': 'Oddish',
    'duflor': 'Gloom',
    'giflor': 'Vileplume',
    'paras': 'Paras',
    'parasek': 'Parasect',
    'bluzuk': 'Venonat',
    'omot': 'Venomoth',
    'knofensa': 'Bellsprout',
    'ultrigaria': 'Victreebel',
    'owei': 'Exeggcute',
    'kokowei': 'Exeggutor',
    'kokowei-ex': 'Exeggutor ex',
    'tangela': 'Tangela',
    'sichlor': 'Scyther',
    'pinsir': 'Pinsir',
    'waumboll': 'Cottonee',
    'elfun': 'Whimsicott',
    'lilminip': 'Lilligant',
    'dressella': 'Leafeon',
    'mähikel': 'Skiddo',
    'chevrumm': 'Gogoat',
    'glumanda': 'Charmander',
    'glutexo': 'Charmeleon',
    'glurak': 'Charizard',
    'glurak-ex': 'Charizard ex',
    'vulpix': 'Vulpix',
    'vulnona': 'Ninetales',
    'fukano': 'Growlithe',
    'arkani': 'Arcanine',
    'arkani-ex': 'Arcanine ex',
    'ponita': 'Ponyta',
    'gallopa': 'Rapidash',
    'magmar': 'Magmar',
    'flamara': 'Flareon',
    'lavados': 'Moltres',
    'lavados-ex': 'Moltres ex',
    'furnifraß': 'Heatmor',
    'molunk': 'Salandit',
    'amfira': 'Salazzle',
    'thermopod': 'Sizzlipede',
    'infernopod': 'Centiskorch',
    'schiggy': 'Squirtle',
    'schillok': 'Wartortle',
    'turtok': 'Blastoise',
    'turtok-ex': 'Blastoise ex',
    'enton': 'Psyduck',
    'entoron': 'Golduck',
    'quapsel': 'Poliwag',
    'quaputzi': 'Poliwhirl',
    'quappo': 'Politoed',
    'tentacha': 'Tentacool',
    'tentoxa': 'Tentacruel',
    'jurob': 'Seel',
    'jugong': 'Dewgong',
    'muschas': 'Shellder',
    'austos': 'Cloyster',
    'krabby': 'Krabby',
    'kingler': 'Kingler',
    'seeper': 'Horsea',
    'seemon': 'Seadra',
    'goldini': 'Goldeen',
    'golking': 'Seaking',
    'sterndu': 'Staryu',
    'starmie': 'Starmie',
    'starmie-ex': 'Starmie ex',
    'karpador': 'Magikarp',
    'garados': 'Gyarados',
    'lapras': 'Lapras',
    'aquana': 'Vaporeon',
    'amonitas': 'Omanyte',
    'amoroso': 'Omastar',
    'arktos': 'Articuno',
    'arktos-ex': 'Articuno ex',
    'piccolente': 'Ducklett',
    'swaroness': 'Swanna',
    'froxy': 'Froakie',
    'amphizel': 'Greninja',
    'quajutsu': 'Greninja',
    'gufa': 'Pyukumuku',
    'knirfish': 'Bruxish',
    'snomnom': 'Snom',
    'mottineva': 'Frosmoth',
    'pikachu': 'Pikachu',
    'raichu': 'Raichu',
    'pikachu-ex': 'Pikachu ex',
    'magnetilo': 'Magnemite',
    'magneton': 'Magneton',
    'voltobal': 'Voltorb',
    'lektrobal': 'Electrode',
    'elektek': 'Electabuzz',
    'blitza': 'Jolteon',
    'zapdos': 'Zapdos',
    'zapdos-ex': 'Zapdos ex',
    'elezeba': 'Blitzle',
    'zebritz': 'Zebstrika',
    'zapplardin': 'Tynamo',
    'zapplalek': 'Eelektrik',
    'zapplarang': 'Eelektross',
    'eguana': 'Helioptile',
    'elezard': 'Heliolisk',
    'britzigel': 'Pincurchin',
    'piepi': 'Clefairy',
    'pixi': 'Clefable',
    'abra': 'Abra',
    'kadabra': 'Kadabra',
    'simsala': 'Alakazam',
    'flegmon': 'Slowpoke',
    'lahmus': 'Slowbro',
    'nebulak': 'Gastly',
    'alpollo': 'Haunter',
    'gengar': 'Gengar',
    'gengar-ex': 'Gengar ex',
    'traumato': 'Drowzee',
    'hypno': 'Hypno',
    'pantimos': 'Mr. Mime',
    'rossana': 'Jynx',
    'mewtu': 'Mewtwo',
    'mewtu-ex': 'Mewtwo ex',
    'trasla': 'Ralts',
    'kirlia': 'Kirlia',
    'guardevoir': 'Gardevoir',
    'fleknoil': 'Woobat',
    'fletiamo': 'Swoobat',
    'golbit': 'Golett',
    'golgantes': 'Golurk',
    'sandan': 'Sandshrew',
    'sandamer': 'Sandslash',
    'digda': 'Diglett',
    'digdri': 'Dugtrio',
    'menki': 'Mankey',
    'rasaff': 'Primeape',
    'machollo': 'Machop',
    'maschock': 'Machoke',
    'machomei': 'Machamp',
    'machomei-ex': 'Machamp ex',
    'kleinstein': 'Geodude',
    'georok': 'Graveler',
    'geowaz': 'Golem',
    'onix': 'Onix',
    'tragosso': 'Cubone',
    'knogga': 'Marowak',
    'knogga-ex': 'Marowak ex',
    'kicklee': 'Hitmonlee',
    'nockchan': 'Hitmonchan',
    'rihorn': 'Rhyhorn',
    'rizeros': 'Rhydon',
    'rihornior': 'Rhyperior',
    'kabuto': 'Kabuto',
    'kabutops': 'Kabutops',
    'lin-fu': 'Mienfoo',
    'wie-shu': 'Mienshao',
    'klopptopus': 'Clobbopus',
    'rettan': 'Ekans',
    'arbok': 'Arbok',
    'zubat': 'Zubat',
    'golbat': 'Golbat',
    'sleima': 'Grimer',
    'sleimok': 'Muk',
    'smogon': 'Koffing',
    'smogmog': 'Weezing',
    'flunkifer': 'Mawile',
    'gladiantri': 'Pawniard',
    'caesurio': 'Kingambit',
    'meltan': 'Meltan',
    'melmetal': 'Melmetal',
    'dratini': 'Dratini',
    'dragonir': 'Dragonair',
    'dragoran': 'Dragonite',
    'taubsi': 'Pidgey',
    'tauboga': 'Pidgeotto',
    'tauboss': 'Pidgeot',
    'rattfratz': 'Rattata',
    'rattikarl': 'Raticate',
    'habitak': 'Spearow',
    'ibitak': 'Fearow',
    'pummeluff': 'Jigglypuff',
    'knuddeluff': 'Wigglytuff',
    'knuddeluff-ex': 'Wigglytuff ex',
    'mauzi': 'Meowth',
    'snobikikat': 'Persian',
    'porenta': 'Farfetch\'d',
    'dodu': 'Doduo',
    'dodri': 'Dodrio',
    'schlurp': 'Lickitung',
    'chaneira': 'Chansey',
    'kangama': 'Kangaskhan',
    'tauros': 'Tauros',
    'ditto': 'Ditto',
    'evoli': 'Eevee',
    'porygon': 'Porygon',
    'aerodactyl': 'Aerodactyl',
    'relaxo': 'Snorlax',
    'picochilla': 'Minccino',
    'chillabell': 'Cinccino',
    'wolly': 'Wooloo',
    'zwollock': 'Dubwool',
    # More Pokemon
    'blubella': 'Bellossom',
    'tangoloss': 'Tangrowth',
    'yanma': 'Yanma',
    'yanmega-ex': 'Yanmega ex',
    'roselia': 'Roselia',
    'roserade': 'Roserade',
    'chelast': 'Turtwig',
    'chelcarain': 'Grotle',
    'chelterrar': 'Torterra',
    'zirpurze': 'Kricketot',
    'zirpeise': 'Kricketune',
    'burmy': 'Burmy',
    'burmadame': 'Wormadam',
    'wadribie': 'Combee',
    'honweisel': 'Vespiquen',
    'venuflibis': 'Carnivine',
    'folipurba': 'Leafeon',
    'shaymin': 'Shaymin',
    'magbrant': 'Magmortar',
    'schneckmag': 'Slugma',
    'magcargo': 'Magcargo',
    'panflam': 'Chimchar',
    'panpyro': 'Monferno',
    'panferno-ex': 'Infernape ex',
    'quiekel': 'Swinub',
    'keifel': 'Piloswine',
    'mamutel': 'Mamoswine',
    'plinfa': 'Piplup',
    'pliprin': 'Prinplup',
    'impoleon': 'Empoleon',
    'bamelin': 'Buizel',
    'bojelin': 'Floatzel',
    'schalellos': 'Shellos',
    'gastrodon': 'Gastrodon',
    'finneon': 'Finneon',
    'lumineon': 'Lumineon',
    'shnebedeck': 'Snover',
    'rexblisar': 'Abomasnow',
    'glaziola': 'Glaceon',
    'palkia-ex': 'Palkia ex',
    'manaphy': 'Manaphy',
    'pachirisu-ex': 'Pachirisu ex',
    'rotom': 'Rotom',
    'togepi': 'Togepi',
    'togetic': 'Togetic',
    'togekiss': 'Togekiss',
    'traunfugil': 'Misdreavus',
    'traunmagil-ex': 'Mismagius ex',
    'zwirrlicht': 'Duskull',
    'zwirrklop': 'Dusclops',
    'zwirrfinst': 'Dusknoir',
    'driftlon': 'Drifloon',
    'drifzepeli': 'Drifblim',
    'selfe': 'Uxie',
    'vesprit': 'Mesprit',
    'tobutz': 'Azelf',
    'giratina': 'Giratina',
    'cresselia': 'Cresselia',
    'skorgla': 'Gligar',
    'skorgro': 'Gliscor',
    'kapoera': 'Hitmontop',
    'nasgnet': 'Nosepass',
    'koknodon': 'Cranidos',
    'rameidon': 'Rampardos',
    'riolu': 'Riolu',
    'lucario': 'Lucario',
    'hippopotas': 'Hippopotas',
    'hippoterus': 'Hippowdon',
    'kobalium': 'Cobalion',
    'kramurx': 'Murkrow',
    'kramshef': 'Honchkrow',
    'sniebel': 'Sneasel',
    'snibunna-ex': 'Weavile ex',
    'fiffyen': 'Poochyena',
    'magnayen': 'Mightyena',
    'skunkapuh': 'Stunky',
    'skuntank': 'Skuntank',
    'kryppuk': 'Spiritomb',
    'pionskora': 'Skorupi',
    'piondragi': 'Drapion',
    'glibunkel': 'Croagunk',
    'toxiquak': 'Toxicroak',
    'darkrai': 'Darkrai',
    'darkrai-ex': 'Darkrai ex',
    'panzaeron': 'Pangoro',
    'registeel': 'Registeel',
    'schilterus': 'Shieldon',
    'bollterus': 'Bastiodon',
    'bronzeel': 'Bronzor',
    'bronzong': 'Bronzong',
    'voluminas': 'Probopass',
    'dialga-ex': 'Dialga ex',
    'heatran': 'Heatran',
    'kaumalat': 'Gible',
    'knarksel': 'Gabite',
    'knakrack': 'Garchomp',
    'schlurplek-ex': 'Lickilicky ex',
    'griffel': 'Aipom',
    'ambidiffel': 'Ambipom',
    'staralili': 'Starly',
    'staravia': 'Staravia',
    'staraptor': 'Staraptor',
    'bidiza': 'Bidoof',
    'bidifas': 'Bibarel',
    'bidifas-ex': 'Bibarel ex',
    'haspiror': 'Buneary',
    'schlapor': 'Lopunny',
    'charmian': 'Glameow',
    'shnurgarst': 'Purugly',
    'plaudagei': 'Chatot',
    'icognito': 'Incognito',
    'phanpy': 'Phanpy',
    'donphan': 'Donphan',
    'larvitar': 'Larvitar',
    'pupitar': 'Pupitar',
    'despotar': 'Tyranitar',
}

if __name__ == '__main__':
    print(f"Total mappings: {len(GERMAN_TO_ENGLISH)}")
